<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'ecfa935f7c6670a0263a6cdf2aafe8ebd16f8d17',
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'ecfa935f7c6670a0263a6cdf2aafe8ebd16f8d17',
            'dev_requirement' => false,
        ),
        'facebook/graph-sdk' => array(
            'pretty_version' => '5.7.0',
            'version' => '5.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facebook/graph-sdk',
            'aliases' => array(),
            'reference' => '2d8250638b33d73e7a87add65f47fabf91f8ad9b',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.1.6',
            'version' => '6.1.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'c2796cb1cb99d7717290b48c4e6f32cb6c60b7b3',
            'dev_requirement' => false,
        ),
        'smarty/smarty' => array(
            'pretty_version' => 'v3.1.36',
            'version' => '3.1.36.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smarty/smarty',
            'aliases' => array(),
            'reference' => 'fd148f7ade295014fff77f89ee3d5b20d9d55451',
            'dev_requirement' => false,
        ),
    ),
);
